FROM ubuntu:20.10

RUN apt update && \
	apt-get install -f -y --no-install-recommends \
	make \
	imagemagick \
	texlive-base \
	texlive-latex-recommended \
	texlive-latex-extra \
	texlive-fonts-extra \
	texlive-science \
	latexmk
